"""
----------------------------------------------
PythonToSW: A Python package that allows you to make Stormworks addons with Python.
https://github.com/Cuh4/PythonToSW
----------------------------------------------

Copyright (C) 2025 Cuh4

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# // Imports
from enum import Enum

# // Main
__all__ = [
    "CallEnum",
    "CallbackEnum"
]

class CallbackEnum(Enum):
    """
    An enum for all the available callbacks in Stormworks.
    """
    
    ONCLEAROILSPILL = "onClearOilSpill"
    ONTICK = "onTick"
    ONCREATE = "onCreate"
    ONDESTROY = "onDestroy"
    ONCUSTOMCOMMAND = "onCustomCommand"
    ONCHATMESSAGE = "onChatMessage"
    ONPLAYERJOIN = "onPlayerJoin"
    ONPLAYERSIT = "onPlayerSit"
    ONPLAYERUNSIT = "onPlayerUnsit"
    ONCHARACTERSIT = "onCharacterSit"
    ONCHARACTERUNSIT = "onCharacterUnsit"
    ONCHARACTERPICKUP = "onCharacterPickup"
    ONCREATURESIT = "onCreatureSit"
    ONCREATUREUNSIT = "onCreatureUnsit"
    ONCREATUREPICKUP = "onCreaturePickup"
    ONEQUIPMENTPICKUP = "onEquipmentPickup"
    ONEQUIPMENTDROP = "onEquipmentDrop"
    ONPLAYERRESPAWN = "onPlayerRespawn"
    ONPLAYERLEAVE = "onPlayerLeave"
    ONToggleMAP = "onToggleMap"
    ONPLAYERDIE = "onPlayerDie"
    ONVEHICLESPAWN = "onVehicleSpawn"
    ONGROUPSPAWN = "onGroupSpawn"
    ONVEHICLEDESPAWN = "onVehicleDespawn"
    ONVEHICLELOAD = "onVehicleLoad"
    ONVEHICLEUNLOAD = "onVehicleUnload"
    ONVEHICLETELEPORT = "onVehicleTeleport"
    ONOBJECTLOAD = "onObjectLoad"
    ONOBJECTUNLOAD = "onObjectUnload"
    ONBUTTONPRESS = "onButtonPress"
    ONSPAWNADDONCOMPONENT = "onSpawnAddonComponent"
    ONVEHICLEDAMAGED = "onVehicleDamaged"
    HTTPREPLY = "httpReply"
    ONFIREEXTINGUISHED = "onFireExtinguished"
    ONFORESTFIRESPAWNED = "onForestFireSpawned"
    ONFORESTFIREEXTINGUISHED = "onForestFireExtinguished"
    ONTORNADO = "onTornado"
    ONMETEOR = "onMeteor"
    ONTUNAMI = "onTsunami"
    ONWHIRLPOOL = "onWhirlpool"
    ONVOLCANO = "onVolcano"
    ONOILSPILL = "onOilSpill"

class CallEnum(Enum):
    """
    An enum for all the available calls in Stormworks.
    """
    
    GETADDONINDEX = "getAddonIndex"
    GETPLAYLISTINDEXCURRENT = "getPlaylistIndexCurrent"
    GETPLAYLISTINDEXBYNAME = "getPlaylistIndexByName"
    GETLOCATIONINDEX = "getLocationIndex"
    SPAWNTHISADDONLOCATION = "spawnThisAddonLocation"
    SPAWNTHISPLAYLISTMISSIONLOCATION = "spawnThisPlaylistMissionLocation"
    SPAWNNAMEDADDONLOCATION = "spawnNamedAddonLocation"
    SPAWNADDONLOCATION = "spawnAddonLocation"
    SPAWNMISSIONLOCATION = "spawnMissionLocation"
    GETADDONPATH = "getAddonPath"
    GETPLAYLISTPATH = "getPlaylistPath"
    GETZONES = "getZones"
    ISINZONE = "isInZone"
    GETADDONCOUNT = "getAddonCount"
    GETPLAYLISTCOUNT = "getPlaylistCount"
    GETADDONDATA = "getAddonData"
    GETPLAYLISTDATA = "getPlaylistData"
    GETLOCATIONDATA = "getLocationData"
    GETLOCATIONCOMPONENTDATA = "getLocationComponentData"
    SPAWNADDONCOMPONENT = "spawnAddonComponent"
    SPAWNMISSIONCOMPONENT = "spawnMissionComponent"
    ANNOUNCE = "announce"
    COMMAND = "command"
    NOTIFY = "notify"
    GETMAPID = "getMapID"
    REMOVEMAPID = "removeMapID"
    ADDMAPOBJECT = "addMapObject"
    REMOVEMAPOBJECT = "removeMapObject"
    ADDMAPLABEL = "addMapLabel"
    REMOVEMAPLABEL = "removeMapLabel"
    ADDMAPLINE = "addMapLine"
    REMOVEMAPLINE = "removeMapLine"
    SETPOPUP = "setPopup"
    SETPOPUPSCREEN = "setPopupScreen"
    REMOVEPOPUP = "removePopup"
    GETPLAYERS = "getPlayers"
    GETPLAYERNAME = "getPlayerName"
    GETPLAYERPOS = "getPlayerPos"
    SETPLAYERPOS = "setPlayerPos"
    GETPLAYERLOOKDIRECTION = "getPlayerLookDirection"
    GETPLAYERCHARACTERID = "getPlayerCharacterID"
    SPAWNOBJECT = "spawnObject"
    SPAWNFIRE = "spawnFire"
    SPAWNCHARACTER = "spawnCharacter"
    SPAWNANIMAL = "spawnAnimal"
    SPAWNCREATURE = "spawnCreature"
    SETCREATUREMOVETARGET = "setCreatureMoveTarget"
    SPAWNEQUIPMENT = "spawnEquipment"
    DESPAWNOBJECT = "despawnObject"
    GETOBJECTPOS = "getObjectPos"
    GETOBJECTSIMULATING = "getObjectSimulating"
    SETOBJECTPOS = "setObjectPos"
    SETFIREDATA = "setFireData"
    GETFIREDATA = "getFireData"
    KILLCHARACTER = "killCharacter"
    REVIVECHARACTER = "reviveCharacter"
    SETSEATED = "setSeated"
    SETCHARACTERSEATED = "setCharacterSeated"
    SETCREATURESEATED = "setCreatureSeated"
    GETOBJECTDATA = "getObjectData"
    GETCHARACTERDATA = "getCharacterData"
    GETCHARACTERVEHICLE = "getCharacterVehicle"
    SETCHARACTERDATA = "setCharacterData"
    SETCHARACTERTOOLTIP = "setCharacterTooltip"
    SETCREATURETOOLTIP = "setCreatureTooltip"
    SETCHARACTERITEM = "setCharacterItem"
    GETCHARACTERITEM = "getCharacterItem"
    SPAWNADDONVEHICLE = "spawnAddonVehicle"
    SPAWNVEHICLE = "spawnVehicle"
    SPAWNVEHICLESAVEFILE = "spawnVehicleSavefile"
    DESPAWNVEHICLE = "despawnVehicle"
    ISLOCATIONCLEAR = "isLocationClear"
    GETVEHICLEPOS = "getVehiclePos"
    SETVEHICLEPOS = "setVehiclePos"
    SETVEHICLEPOSSAFE = "setVehiclePosSafe"
    RESETVEHICLESTATE = "resetVehicleState"
    CLEANVEHICLES = "cleanVehicles"
    CLEARRADIATION = "clearRadiation"
    GETVEHICLEDATA = "getVehicleData"
    GETVEHICLESBYNAME = "getVehiclesByName"
    GETVEHICLECOMPONENTS = "getVehicleComponents"
    GETVEHICLEGROUP = "getVehicleGroup"
    DESPAWNVEHICLEGROUP = "despawnVehicleGroup"
    SETGROUPPOS = "setGroupPos"
    MOVEGROUP = "moveGroup"
    MOVEGROUPSAFE = "moveGroupSafe"
    MOVEVEHICLE = "moveVehicle"
    MOVEVEHICLESAFE = "moveVehicleSafe"
    SETGROUPPOSSAFE = "setGroupPosSafe"
    GETASTROPOS = "getAstroPos"
    GETVEHICLETANK = "getVehicleTank"
    GETVEHICLESIGN = "getVehicleSign"
    GETVEHICLESEAT = "getVehicleSeat"
    GETVEHICLEBUTTON = "getVehicleButton"
    GETVEHICLEDIAL = "getVehicleDial"
    GETVEHICLEBATTERY = "getVehicleBattery"
    GETVEHICLEHOPPER = "getVehicleHopper"
    GETVEHICLEWEAPON = "getVehicleWeapon"
    GETVEHICLEROPEHOOK = "getVehicleRopeHook"
    SETVEHICLESEAT = "setVehicleSeat"
    PRESSVEHICLEBUTTON = "pressVehicleButton"
    SETVEHICLEKEYPAD = "setVehicleKeypad"
    SETVEHICLETANK = "setVehicleTank"
    SETVEHICLEBATTERY = "setVehicleBattery"
    SETVEHICLEHOPPER = "setVehicleHopper"
    SETVEHICLEWEAPON = "setVehicleWeapon"
    SPAWNVEHICLEROPE = "spawnVehicleRope"
    GETVEHICLEFIRECOUNT = "getVehicleFireCount"
    SETVEHICLETOOLTIP = "setVehicleTooltip"
    ADDDAMAGE = "addDamage"
    GETVEHICLESIMULATING = "getVehicleSimulating"
    GETVEHICLELOCAL = "getVehicleLocal"
    SETVEHICLETRANSPONDER = "setVehicleTransponder"
    SETVEHICLEEDITABLE = "setVehicleEditable"
    SETVEHICLEINVULNERABLE = "setVehicleInvulnerable"
    SETVEHICLESHOWONMAP = "setVehicleShowOnMap"
    SETAISTATE = "setAIState"
    SETAITARGET = "setAITarget"
    GETAITARGET = "getAITarget"
    SETAITARGETCHARACTER = "setAITargetCharacter"
    SETAITARGETVEHICLE = "setAITargetVehicle"
    SETAICHARACTERTEAM = "setAICharacterTeam"
    SETAIVEHICLETEAM = "setAIVehicleTeam"
    SETAICHARACTERTARGETTEAM = "setAICharacterTargetTeam"
    GETFISHDATA = "getFishData"
    GETFISHHOTSPOTS = "getFishHotspots"
    SPAWNTSUNAMI = "spawnTsunami"
    SPAWNWHIRLPOOL = "spawnWhirlpool"
    CANCELGERSTNER = "cancelGerstner"
    SPAWNTORNADO = "spawnTornado"
    SPAWNMETEOR = "spawnMeteor"
    SPAWNMETEORSHOWER = "spawnMeteorShower"
    SPAWNVOLCANO = "spawnVolcano"
    GETVOLCANOS = "getVolcanos"
    GETOILSPILL = "getOilSpill"
    SETOILSPILL = "setOilSpill"
    CLEAROILSPILL = "clearOilSpill"
    SPAWNEXPLOSION = "spawnExplosion"
    SETGAMESETTING = "setGameSetting"
    GETGAMESETTINGS = "getGameSettings"
    SETCURRENCY = "setCurrency"
    GETCURRENCY = "getCurrency"
    GETRESEARCHPOINTS = "getResearchPoints"
    GETDATEVALUE = "getDateValue"
    GETDATE = "getDate"
    GETTIME = "getTime"
    GETWEATHER = "getWeather"
    SETWEATHER = "setWeather"
    SETAUDIOMOOD = "setAudioMood"
    GETOCEANTRANSFORM = "getOceanTransform"
    GETOCEANFLOOR = "getOceanFloor"
    GETTILETRANSFORM = "getTileTransform"
    GETTILE = "getTile"
    GETSTARTTILE = "getStartTile"
    GETSTARTISLAND = "getStartIsland"
    GETTILEPURCHASED = "getTilePurchased"
    GETTILEINVENTORY = "getTileInventory"
    SETTILEINVENTORY = "setTileInventory"
    ISINTRANSFORMAREA = "isInTransformArea"
    PATHFIND = "pathfind"
    PATHFINDOCEAN = "pathfindOcean"
    GETOILDEPOSITS = "getOilDeposits"
    BANPLAYER = "banPlayer"
    KICKPLAYER = "kickPlayer"
    ADDADMIN = "addAdmin"
    REMOVEADMIN = "removeAdmin"
    ADDAUTH = "addAuth"
    REMOVEAUTH = "removeAuth"
    SAVE = "save"
    GETTIMEMILLISEC = "getTimeMillisec"
    GETTUTORIAL = "getTutorial"
    SETTUTORIAL = "setTutorial"
    GETVIDEOTUTORIAL = "getVideoTutorial"
    ISDEV = "isDev"
    DLCWEAPONS = "dlcWeapons"
    DLCARID = "dlcArid"
    DLCSPACE = "dlcSpace"
    GETSEASONALEVENT = "getSeasonalEvent"